language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker pull acroz/livy
  - docker run --publish 8998:8998 acroz/livy &
  - sleep 10
script:
  - pip install flake8 .
  - flake8
  - python setup.py it
