version: 2
jobs:
  flake8:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: tox -e flake8
  mypy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: tox -e mypy
  black:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: tox -e black
  python3.6:
    docker:
      - image: circleci/python:3.6
      - image: acroz/livy
    steps:
      - checkout
      - run:
          command: tox -e py36-integration
  python3.7:
    docker:
      - image: circleci/python:3.7
      - image: acroz/livy
    steps:
      - checkout
      - run:
          command: tox -e py37-integration
